// <auto-generated />
namespace AgricultureManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migra_test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migra_test));
        
        string IMigrationMetadata.Id
        {
            get { return "202110150604479_migra_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
